language: objective-c

before_install:
  - sudo gem install xcpretty

branches:
  only:
  - master

xcode_project: TextFieldCounter/TextFieldCounter.xcodeproj
xcode_scheme: TextFieldCounter

osx_image: xcode8.2
xcode_sdk: iphonesimulator9.3
